name: publish-docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - run: npm ci
      - run: npx aegir docs --publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
